//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportApplication.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAO_CAO_TT35
    {
        public int ID { get; set; }
        public Nullable<int> MENU_CHA { get; set; }
        public string FRM_CODE { get; set; }
        public string FRM_NAME { get; set; }
        public string FRM_DES { get; set; }
        public bool STATUS { get; set; }
        public Nullable<bool> DATA_STATUS { get; set; }
        public Nullable<bool> BC_ALL { get; set; }
    }
}
