//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportApplication.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAO_CAO_TT35_MENU
    {
        public int ID { get; set; }
        public string MENU_CODE { get; set; }
        public string MENU_NAME { get; set; }
        public bool STATUS { get; set; }
    }
}
