//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportApplication.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_DON_VI
    {
        public int ID { get; set; }
        public Nullable<int> ID_DVI_CHA { get; set; }
        public string MA_DVI { get; set; }
        public string MA_DVI_CHA { get; set; }
        public string LOAI_DVI { get; set; }
        public string MA_TINHTP { get; set; }
        public string NGUON_TAO_DL { get; set; }
        public string MA_NHNN { get; set; }
        public string NGAY_HDONG { get; set; }
        public string TEN_GDICH { get; set; }
        public string TEN_TAT { get; set; }
        public string DIA_CHI { get; set; }
        public string DIEN_THOAI { get; set; }
        public string SO_FAX { get; set; }
        public string WEBSITE { get; set; }
        public string EMAIL { get; set; }
        public string LOGO { get; set; }
        public string SO_DKKD { get; set; }
        public string MA_SO_THUE { get; set; }
        public string SO_TAI_KHOAN { get; set; }
        public string TEN_NGAN_HANG { get; set; }
        public string MA_HACH_TOAN { get; set; }
        public string GDOC_TEN { get; set; }
        public string GDOC_TEL { get; set; }
        public string GDOC_MOBILE { get; set; }
        public string GDOC_FAX { get; set; }
        public string GDOC_EMAIL { get; set; }
        public string KTTRUONG_TEN { get; set; }
        public string KTTRUONG_TEL { get; set; }
        public string KTTRUONG_MOBILE { get; set; }
        public string KTTRUONG_FAX { get; set; }
        public string KTTRUONG_EMAIL { get; set; }
        public string MA_TSUAT { get; set; }
        public string TTHAI_BGHI { get; set; }
        public string TTHAI_NVU { get; set; }
        public string MA_DVI_QLY { get; set; }
        public string MA_DVI_TAO { get; set; }
        public string NGAY_NHAP { get; set; }
        public string NGUOI_NHAP { get; set; }
        public string NGAY_CNHAT { get; set; }
        public string NGUOI_CNHAT { get; set; }
        public string TTHAI_LY_DO { get; set; }
    }
}
