//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportApplication.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_NSD
    {
        public int ID { get; set; }
        public string MA_NSD { get; set; }
        public string MA_DANG_NHAP { get; set; }
        public string PHAN_LOAI_NSD { get; set; }
        public string MAT_KHAU { get; set; }
        public string MA_HSO { get; set; }
        public string TEN_GOI { get; set; }
        public string TEN_HO_DEM { get; set; }
        public string TEN_DAY_DU { get; set; }
        public string EMAIL { get; set; }
        public string DIEN_THOAI { get; set; }
        public string NGAY_SINH { get; set; }
        public string GIOI_TINH { get; set; }
        public string TDOI_MKHAU { get; set; }
        public string NGAY_TAO { get; set; }
        public string NGAY_HIEU_LUC { get; set; }
        public string NGAY_HET_HAN { get; set; }
        public Nullable<int> TGIAN_DOI_MKHAU { get; set; }
        public string TGIAN_DOI_DVI_TINH { get; set; }
        public string NGAY_DOI_MKHAU { get; set; }
        public string NGUON_TAO_DL { get; set; }
        public string TINH_TRANG { get; set; }
        public string HAN_CHE_TRUY_CAP { get; set; }
        public string TTHAI_BGHI { get; set; }
        public string TTHAI_NVU { get; set; }
        public string MA_DVI_QLY { get; set; }
        public string MA_DVI_TAO { get; set; }
        public string NGAY_NHAP { get; set; }
        public string NGUOI_NHAP { get; set; }
        public string NGAY_CNHAT { get; set; }
        public string NGUOI_CNHAT { get; set; }
        public string TTHAI_LY_DO { get; set; }
    }
}
