//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportApplication.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReportApplicationEntities : DbContext
    {
        public ReportApplicationEntities()
            : base("name=ReportApplicationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAO_CAO_TT35_MENU> BAO_CAO_TT35_MENU { get; set; }
        public virtual DbSet<DM_DON_VI> DM_DON_VI { get; set; }
        public virtual DbSet<HT_NSD> HT_NSD { get; set; }
        public virtual DbSet<BAO_CAO_TT35> BAO_CAO_TT35 { get; set; }
        public virtual DbSet<TT35_LAI_SUAT_G01254> TT35_LAI_SUAT_G01254 { get; set; }
    }
}
