//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportApplication.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT35_LAI_SUAT_G01254
    {
        public int ID { get; set; }
        public string NGAY_DL { get; set; }
        public string MA_LAI_SUAT { get; set; }
        public decimal LAI_SUAT { get; set; }
        public Nullable<int> KY_HAN { get; set; }
        public string DV_TINH { get; set; }
    }
}
